import subprocess
from pathlib import Path


def build_project(folder_name: str, config: dict):
    project_path = Path(folder_name).resolve()
    project_path.mkdir(parents=True, exist_ok=True)

    subdirs = ["agent", "tools", "models", "prompts", "storage", "utils", "api"]
    for sd in subdirs:
        (project_path / "src" / sd).mkdir(parents=True, exist_ok=True)
        (project_path / "src" / sd / "__init__.py").touch()

    (project_path / "tests").mkdir(exist_ok=True)
    (project_path / "tests" / "__init__.py").touch()

    pkgs = ["pydantic", "pydantic-settings", "python-dotenv", "pytest", "pytest-asyncio"]

    if "LangGraph" in config["framework"]:
        pkgs.extend(["langgraph", "langchain-core"])
    elif "CrewAI" in config["framework"]:
        pkgs.append("crewai")
    elif "PydanticAI" in config["framework"]:
        pkgs.append("pydantic-ai")
    elif "AutoGen" in config["framework"]:
        pkgs.extend(["autogen-agentchat", "autogen-ext"])

    if "OpenAI" in config["provider"]:
        pkgs.extend(["openai", "langchain-openai"])
    elif "Anthropic" in config["provider"]:
        pkgs.extend(["anthropic", "langchain-anthropic"])
    elif "Groq" in config["provider"]:
        pkgs.extend(["groq", "langchain-groq"])
    elif "DeepSeek" in config["provider"]:
        pkgs.append("openai")

    if "Qdrant" in config["storage"]:
        pkgs.append("qdrant-client")
    elif "PostgreSQL" in config["storage"]:
        pkgs.extend(["psycopg2-binary", "pgvector", "sqlalchemy"])
    elif "Redis" in config["storage"]:
        pkgs.append("redis")

    if "LangSmith" in config["logging"]:
        pkgs.append("langsmith")
    elif "Arize" in config["logging"]:
        pkgs.append("arize-phoenix")
    elif "Loguru" in config["logging"]:
        pkgs.append("loguru")

    subprocess.run(
        ["uv", "init"],
        cwd=project_path,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    subprocess.run(
        ["uv", "add"] + pkgs,
        cwd=project_path,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    with open(project_path / ".env", "w", encoding="utf-8") as f:
        f.write("# API keys and settings generated by ainit\n")
        if "OpenAI" in config["provider"]:
            f.write("OPENAI_API_KEY=your_key_here\n")
        elif "Anthropic" in config["provider"]:
            f.write("ANTHROPIC_API_KEY=your_key_here\n")
        elif "Groq" in config["provider"]:
            f.write("GROQ_API_KEY=your_key_here\n")
        elif "DeepSeek" in config["provider"]:
            f.write("DEEPSEEK_API_KEY=your_key_here\n")

    with open(project_path / "src" / "models" / "llm.py", "w", encoding="utf-8") as f:
        f.write('''import os
from dotenv import load_dotenv

load_dotenv()

def get_llm():
    """Return the initialized LLM client."""
    api_key = os.getenv("OPENAI_API_KEY") or os.getenv("GROQ_API_KEY") or os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError("API key is not configured in the .env file")
    return {"status": "configured", "api_key_present": True}
''')

    with open(project_path / "main.py", "w", encoding="utf-8") as f:
        f.write('''from src.models.llm import get_llm

def main():
    print("🤖 Agent project initialized successfully!")
    client = get_llm()
    print("Model status:", client)

if __name__ == "__main__":
    main()
''')

    with open(project_path / "tests" / "test_smoke.py", "w", encoding="utf-8") as f:
        f.write('''import os

def test_env_file_exists():
    assert os.path.exists(".env")

def test_llm_module_import():
    from src.models.llm import get_llm
    assert callable(get_llm)
''')
